project_id = "qiupqrmtxwtgipbwcvoo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.process-payment]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false