project_id = "qiupqrmtxwtgipbwcvoo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-admin-notification]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false

[functions.send-user-notification]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.check-pending-orders]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.swychr-auth]
verify_jwt = false

[functions.swychr-create-payment]
verify_jwt = false

[functions.swychr-status]
verify_jwt = false

[functions.swychr-webhook]
verify_jwt = false

[functions.offline-payment]
verify_jwt = false