import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

export type OperationalOrderType = "food" | "errand" | "parcel" | "custom";
export type OperationalOrderSource = "whatsapp" | "phone_call" | "walk_in" | "emergency";
export type OperationalOrderStatus = "pending" | "assigned" | "picked_up" | "in_transit" | "delivered" | "cancelled" | "failed";

export interface OperationalOrder {
  id: string;
  reference_id: string;
  order_type: OperationalOrderType;
  order_source: OperationalOrderSource;
  customer_name: string;
  customer_phone: string;
  pickup_location: string;
  dropoff_location: string;
  description: string | null;
  estimated_amount: number;
  actual_amount: number | null;
  payment_method: string;
  payment_status: string;
  status: OperationalOrderStatus;
  assigned_rider_id: string | null;
  created_by: string;
  town: string;
  is_deleted: boolean;
  created_at: string;
  updated_at: string;
  rider?: Rider | null;
}

export interface Rider {
  id: string;
  name: string;
  phone: string;
  email: string | null;
  is_active: boolean;
  current_status: "available" | "busy" | "offline";
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface OrderActivityLog {
  id: string;
  operational_order_id: string;
  action_type: string;
  action_by: string;
  previous_value: Record<string, unknown> | null;
  new_value: Record<string, unknown> | null;
  notes: string | null;
  created_at: string;
}

export interface OrderNote {
  id: string;
  operational_order_id: string;
  note: string;
  created_by: string;
  is_deleted: boolean;
  created_at: string;
}

export interface CreateOrderInput {
  order_type: OperationalOrderType;
  order_source: OperationalOrderSource;
  customer_name: string;
  customer_phone: string;
  pickup_location: string;
  dropoff_location: string;
  description?: string;
  estimated_amount: number;
  payment_method: string;
  town?: string;
}

export const useOperationalOrders = (statusFilter?: OperationalOrderStatus | "today" | "delayed" | "all") => {
  const [orders, setOrders] = useState<OperationalOrder[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  const fetchOrders = async () => {
    try {
      setLoading(true);
      let query = supabase
        .from("operational_orders")
        .select(`
          *,
          rider:riders(*)
        `)
        .eq("is_deleted", false)
        .order("created_at", { ascending: false });

      if (statusFilter === "today") {
        const today = new Date().toISOString().split("T")[0];
        query = query.gte("created_at", today);
      } else if (statusFilter === "delayed") {
        // Orders that are pending or assigned for more than 1 hour
        const oneHourAgo = new Date(Date.now() - 60 * 60 * 1000).toISOString();
        query = query
          .in("status", ["pending", "assigned"])
          .lt("created_at", oneHourAgo);
      } else if (statusFilter && statusFilter !== "all") {
        query = query.eq("status", statusFilter);
      }

      const { data, error } = await query;

      if (error) throw error;
      setOrders((data as unknown as OperationalOrder[]) || []);
    } catch (error) {
      console.error("Error fetching operational orders:", error);
      toast({
        title: "Error",
        description: "Failed to fetch orders",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchOrders();
  }, [statusFilter]);

  const createOrder = async (input: CreateOrderInput): Promise<OperationalOrder | null> => {
    try {
      const { data: userData } = await supabase.auth.getUser();
      if (!userData.user) throw new Error("Not authenticated");

      const { data, error } = await supabase
        .from("operational_orders")
        .insert({
          ...input,
          created_by: userData.user.id,
          reference_id: "", // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;

      toast({
        title: "Order Created",
        description: `Order ${data.reference_id} created successfully`,
      });

      await fetchOrders();
      return data as unknown as OperationalOrder;
    } catch (error) {
      console.error("Error creating order:", error);
      toast({
        title: "Error",
        description: "Failed to create order",
        variant: "destructive",
      });
      return null;
    }
  };

  const updateOrderStatus = async (orderId: string, status: OperationalOrderStatus): Promise<boolean> => {
    try {
      const { error } = await supabase
        .from("operational_orders")
        .update({ status })
        .eq("id", orderId);

      if (error) throw error;

      toast({
        title: "Status Updated",
        description: `Order status changed to ${status}`,
      });

      await fetchOrders();
      return true;
    } catch (error) {
      console.error("Error updating order status:", error);
      toast({
        title: "Error",
        description: "Failed to update order status",
        variant: "destructive",
      });
      return false;
    }
  };

  const assignRider = async (orderId: string, riderId: string): Promise<boolean> => {
    try {
      const { error } = await supabase
        .from("operational_orders")
        .update({ 
          assigned_rider_id: riderId,
          status: "assigned" as OperationalOrderStatus
        })
        .eq("id", orderId);

      if (error) throw error;

      toast({
        title: "Rider Assigned",
        description: "Rider has been assigned to this order",
      });

      await fetchOrders();
      return true;
    } catch (error) {
      console.error("Error assigning rider:", error);
      toast({
        title: "Error",
        description: "Failed to assign rider",
        variant: "destructive",
      });
      return false;
    }
  };

  const softDeleteOrder = async (orderId: string): Promise<boolean> => {
    try {
      const { data: userData } = await supabase.auth.getUser();
      
      const { error } = await supabase
        .from("operational_orders")
        .update({ 
          is_deleted: true,
          deleted_at: new Date().toISOString(),
          deleted_by: userData.user?.id
        })
        .eq("id", orderId);

      if (error) throw error;

      toast({
        title: "Order Archived",
        description: "Order has been archived",
      });

      await fetchOrders();
      return true;
    } catch (error) {
      console.error("Error archiving order:", error);
      toast({
        title: "Error",
        description: "Failed to archive order",
        variant: "destructive",
      });
      return false;
    }
  };

  return {
    orders,
    loading,
    refetch: fetchOrders,
    createOrder,
    updateOrderStatus,
    assignRider,
    softDeleteOrder,
  };
};

export const useRiders = () => {
  const [riders, setRiders] = useState<Rider[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  const fetchRiders = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from("riders")
        .select("*")
        .eq("is_active", true)
        .order("name");

      if (error) throw error;
      setRiders((data as unknown as Rider[]) || []);
    } catch (error) {
      console.error("Error fetching riders:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRiders();
  }, []);

  const createRider = async (input: { name: string; phone: string; email?: string }): Promise<Rider | null> => {
    try {
      const { data, error } = await supabase
        .from("riders")
        .insert(input)
        .select()
        .single();

      if (error) throw error;

      toast({
        title: "Rider Added",
        description: `${input.name} has been added as a rider`,
      });

      await fetchRiders();
      return data as unknown as Rider;
    } catch (error) {
      console.error("Error creating rider:", error);
      toast({
        title: "Error",
        description: "Failed to add rider",
        variant: "destructive",
      });
      return null;
    }
  };

  const updateRiderStatus = async (riderId: string, status: Rider["current_status"]): Promise<boolean> => {
    try {
      const { error } = await supabase
        .from("riders")
        .update({ current_status: status })
        .eq("id", riderId);

      if (error) throw error;
      await fetchRiders();
      return true;
    } catch (error) {
      console.error("Error updating rider status:", error);
      return false;
    }
  };

  return {
    riders,
    loading,
    refetch: fetchRiders,
    createRider,
    updateRiderStatus,
  };
};

export const useOrderActivityLog = (orderId: string) => {
  const [activities, setActivities] = useState<OrderActivityLog[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchActivities = async () => {
      try {
        setLoading(true);
        const { data, error } = await supabase
          .from("order_activity_log")
          .select("*")
          .eq("operational_order_id", orderId)
          .order("created_at", { ascending: false });

        if (error) throw error;
        setActivities((data as OrderActivityLog[]) || []);
      } catch (error) {
        console.error("Error fetching activity log:", error);
      } finally {
        setLoading(false);
      }
    };

    if (orderId) {
      fetchActivities();
    }
  }, [orderId]);

  return { activities, loading };
};

export const useOrderNotes = (orderId: string) => {
  const [notes, setNotes] = useState<OrderNote[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  const fetchNotes = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from("order_notes")
        .select("*")
        .eq("operational_order_id", orderId)
        .eq("is_deleted", false)
        .order("created_at", { ascending: false });

      if (error) throw error;
      setNotes((data as OrderNote[]) || []);
    } catch (error) {
      console.error("Error fetching order notes:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (orderId) {
      fetchNotes();
    }
  }, [orderId]);

  const addNote = async (note: string): Promise<boolean> => {
    try {
      const { data: userData } = await supabase.auth.getUser();
      if (!userData.user) throw new Error("Not authenticated");

      const { error } = await supabase
        .from("order_notes")
        .insert({
          operational_order_id: orderId,
          note,
          created_by: userData.user.id,
        });

      if (error) throw error;

      toast({
        title: "Note Added",
        description: "Note has been added to this order",
      });

      await fetchNotes();
      return true;
    } catch (error) {
      console.error("Error adding note:", error);
      toast({
        title: "Error",
        description: "Failed to add note",
        variant: "destructive",
      });
      return false;
    }
  };

  return { notes, loading, addNote, refetch: fetchNotes };
};
